// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "right_r.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic right_r::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic right_r::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> right_r::ap_ST_st1_fsm_0 = "00000";
const sc_lv<5> right_r::ap_ST_st2_fsm_1 = "1";
const sc_lv<5> right_r::ap_ST_st3_fsm_2 = "10";
const sc_lv<5> right_r::ap_ST_st4_fsm_3 = "11";
const sc_lv<5> right_r::ap_ST_st5_fsm_4 = "100";
const sc_lv<5> right_r::ap_ST_st6_fsm_5 = "101";
const sc_lv<5> right_r::ap_ST_st7_fsm_6 = "110";
const sc_lv<5> right_r::ap_ST_st8_fsm_7 = "111";
const sc_lv<5> right_r::ap_ST_st9_fsm_8 = "1000";
const sc_lv<5> right_r::ap_ST_st10_fsm_9 = "1001";
const sc_lv<5> right_r::ap_ST_st11_fsm_10 = "1010";
const sc_lv<5> right_r::ap_ST_st12_fsm_11 = "1011";
const sc_lv<5> right_r::ap_ST_st13_fsm_12 = "1100";
const sc_lv<5> right_r::ap_ST_st14_fsm_13 = "1101";
const sc_lv<5> right_r::ap_ST_st15_fsm_14 = "1110";
const sc_lv<5> right_r::ap_ST_st16_fsm_15 = "1111";
const sc_lv<5> right_r::ap_ST_st17_fsm_16 = "10000";
const sc_lv<5> right_r::ap_ST_st18_fsm_17 = "10001";
const sc_lv<5> right_r::ap_ST_st19_fsm_18 = "10010";
const sc_lv<5> right_r::ap_ST_st20_fsm_19 = "10011";
const sc_lv<5> right_r::ap_ST_st21_fsm_20 = "10100";
const sc_lv<1> right_r::ap_const_lv1_0 = "0";
const sc_lv<36> right_r::ap_const_lv36_FFFFFFFFF = "111111111111111111111111111111111111";
const sc_lv<1> right_r::ap_const_lv1_1 = "1";
const sc_lv<2> right_r::ap_const_lv2_0 = "00";
const sc_lv<2> right_r::ap_const_lv2_1 = "1";
const sc_lv<2> right_r::ap_const_lv2_3 = "11";
const sc_lv<36> right_r::ap_const_lv36_1 = "1";
const sc_lv<8> right_r::ap_const_lv8_FF = "11111111";
const sc_lv<8> right_r::ap_const_lv8_0 = "00000000";
const sc_lv<32> right_r::ap_const_lv32_7 = "111";
const sc_lv<2> right_r::ap_const_lv2_2 = "10";
const sc_lv<8> right_r::ap_const_lv8_1 = "1";
const sc_lv<36> right_r::ap_const_lv36_0 = "000000000000000000000000000000000000";

right_r::right_r(sc_module_name name) : sc_module(name), mVcdFile(0) {
    toplevel_sdiv_9s_9ns_9_12_U11 = new toplevel_sdiv_9s_9ns_9_12<11,12,9,9,9>("toplevel_sdiv_9s_9ns_9_12_U11");
    toplevel_sdiv_9s_9ns_9_12_U11->clk(ap_clk);
    toplevel_sdiv_9s_9ns_9_12_U11->reset(ap_rst);
    toplevel_sdiv_9s_9ns_9_12_U11->start(toplevel_sdiv_9s_9ns_9_12_U11_ap_start);
    toplevel_sdiv_9s_9ns_9_12_U11->din0(grp_fu_254_p0);
    toplevel_sdiv_9s_9ns_9_12_U11->din1(grp_fu_254_p1);
    toplevel_sdiv_9s_9ns_9_12_U11->ce(grp_fu_254_ce);
    toplevel_sdiv_9s_9ns_9_12_U11->dout(grp_fu_254_p2);
    toplevel_sdiv_9s_9ns_9_12_U12 = new toplevel_sdiv_9s_9ns_9_12<12,12,9,9,9>("toplevel_sdiv_9s_9ns_9_12_U12");
    toplevel_sdiv_9s_9ns_9_12_U12->clk(ap_clk);
    toplevel_sdiv_9s_9ns_9_12_U12->reset(ap_rst);
    toplevel_sdiv_9s_9ns_9_12_U12->start(toplevel_sdiv_9s_9ns_9_12_U12_ap_start);
    toplevel_sdiv_9s_9ns_9_12_U12->din0(grp_fu_263_p0);
    toplevel_sdiv_9s_9ns_9_12_U12->din1(grp_fu_263_p1);
    toplevel_sdiv_9s_9ns_9_12_U12->ce(grp_fu_263_ce);
    toplevel_sdiv_9s_9ns_9_12_U12->dout(grp_fu_263_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_agg_result_V_i1_fu_349_p3);
    sensitive << ( colours_V_q0 );
    sensitive << ( tmp_26_reg_512 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );
    sensitive << ( p_0_phi_fu_172_p6 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_ap_sig_bdd_157);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );

    SC_METHOD(thread_ap_sig_bdd_390);
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    SC_METHOD(thread_avail_V_o);
    sensitive << ( ap_CS_fsm );
    sensitive << ( avail_V_i );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( possible_V_fu_224_p2 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );
    sensitive << ( tmp_6_fu_409_p2 );

    SC_METHOD(thread_avail_V_o_ap_vld);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    SC_METHOD(thread_colours_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_30_i_fu_301_p1 );
    sensitive << ( tmp_i5_fu_344_p1 );

    SC_METHOD(thread_colours_V_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_184_p2);
    sensitive << ( pp_rot_V_q0 );

    SC_METHOD(thread_grp_fu_254_ce);

    SC_METHOD(thread_grp_fu_254_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( left_V_fu_236_p2 );

    SC_METHOD(thread_grp_fu_254_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_40_tr_i_fu_250_p1 );

    SC_METHOD(thread_grp_fu_263_ce);

    SC_METHOD(thread_grp_fu_263_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( cp_V );

    SC_METHOD(thread_grp_fu_263_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_40_tr_i_fu_250_p1 );

    SC_METHOD(thread_left_V_fu_236_p2);
    sensitive << ( cp_V );

    SC_METHOD(thread_p_0_phi_fu_172_p6);
    sensitive << ( tmp_3_fu_372_p2 );
    sensitive << ( p_0_reg_168 );
    sensitive << ( ap_sig_bdd_390 );
    sensitive << ( ap_sig_bdd_157 );

    SC_METHOD(thread_p_s_fu_403_p2);
    sensitive << ( r_V_10_fu_381_p2 );

    SC_METHOD(thread_possible_V_fu_224_p2);
    sensitive << ( avail_V_i );
    sensitive << ( r_V_fu_214_p2 );

    SC_METHOD(thread_pp_rot_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_fu_199_p1 );
    sensitive << ( pp_rot_V_addr_reg_433 );
    sensitive << ( tmp_i_i_fu_283_p1 );
    sensitive << ( tmp_i_i2_fu_319_p1 );

    SC_METHOD(thread_pp_rot_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_pp_rot_V_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_fu_184_p2 );

    SC_METHOD(thread_pp_rot_V_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_fu_204_p2 );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    SC_METHOD(thread_pp_tile_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_reg_428 );
    sensitive << ( pp_tile_V_addr_reg_442 );
    sensitive << ( tmp_i_i_fu_283_p1 );
    sensitive << ( tmp_i_i2_fu_319_p1 );

    SC_METHOD(thread_pp_tile_V_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_pp_tile_V_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( t_V_fu_365_p2 );

    SC_METHOD(thread_pp_tile_V_we0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    SC_METHOD(thread_r_V_10_fu_381_p2);
    sensitive << ( tmp_4_fu_377_p1 );

    SC_METHOD(thread_r_V_2_fu_392_p2);
    sensitive << ( tmp1_reg_547 );
    sensitive << ( tmp2_fu_387_p2 );

    SC_METHOD(thread_r_V_5_fu_269_p1);
    sensitive << ( grp_fu_254_p2 );

    SC_METHOD(thread_r_V_7_fu_325_p2);
    sensitive << ( pp_rot_V_q0 );

    SC_METHOD(thread_r_V_8_fu_273_p1);
    sensitive << ( grp_fu_263_p2 );

    SC_METHOD(thread_r_V_fu_214_p2);
    sensitive << ( tmp_1_fu_210_p1 );

    SC_METHOD(thread_t_V_fu_365_p2);
    sensitive << ( p_058_0_in_reg_159 );

    SC_METHOD(thread_tiles_V_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_20_fu_296_p1 );
    sensitive << ( tmp_22_fu_339_p1 );

    SC_METHOD(thread_tiles_V_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_tmp1_fu_360_p2);
    sensitive << ( possible_V_reg_452 );
    sensitive << ( agg_result_V_i_reg_145 );

    SC_METHOD(thread_tmp2_fu_387_p2);
    sensitive << ( agg_result_V_i1_reg_537 );
    sensitive << ( r_V_10_fu_381_p2 );

    SC_METHOD(thread_tmp_19_fu_288_p3);
    sensitive << ( pp_tile_V_q0 );
    sensitive << ( grp_fu_184_p2 );

    SC_METHOD(thread_tmp_1_fu_210_p1);
    sensitive << ( pp_tile_V_q0 );

    SC_METHOD(thread_tmp_20_fu_296_p1);
    sensitive << ( tmp_19_fu_288_p3 );

    SC_METHOD(thread_tmp_21_fu_331_p3);
    sensitive << ( pp_tile_V_q0 );
    sensitive << ( r_V_7_fu_325_p2 );

    SC_METHOD(thread_tmp_22_fu_339_p1);
    sensitive << ( tmp_21_fu_331_p3 );

    SC_METHOD(thread_tmp_30_i_fu_301_p1);
    sensitive << ( tiles_V_q0 );

    SC_METHOD(thread_tmp_3_fu_372_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ntiles_V );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( t_V_fu_365_p2 );

    SC_METHOD(thread_tmp_40_tr_i_fu_250_p1);
    sensitive << ( side_V );

    SC_METHOD(thread_tmp_4_fu_377_p1);
    sensitive << ( t_V_fu_365_p2 );

    SC_METHOD(thread_tmp_5_fu_397_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_3_fu_372_p2 );
    sensitive << ( r_V_2_fu_392_p2 );

    SC_METHOD(thread_tmp_6_fu_409_p2);
    sensitive << ( possible_V_reg_452 );
    sensitive << ( p_s_fu_403_p2 );

    SC_METHOD(thread_tmp_fu_199_p1);
    sensitive << ( cp_V );

    SC_METHOD(thread_tmp_i5_fu_344_p1);
    sensitive << ( tiles_V_q0 );

    SC_METHOD(thread_tmp_i_24_fu_277_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( r_V_5_fu_269_p1 );
    sensitive << ( r_V_8_fu_273_p1 );

    SC_METHOD(thread_tmp_i_fu_241_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( cp_V );

    SC_METHOD(thread_tmp_i_i2_fu_319_p1);
    sensitive << ( up_V_fu_306_p2 );

    SC_METHOD(thread_tmp_i_i_fu_283_p1);
    sensitive << ( left_V_reg_458 );

    SC_METHOD(thread_tmp_s_fu_204_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( pp_rot_V_q0 );

    SC_METHOD(thread_toplevel_sdiv_9s_9ns_9_12_U11_ap_start);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_i_fu_241_p2 );

    SC_METHOD(thread_toplevel_sdiv_9s_9ns_9_12_U12_ap_start);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_i_fu_241_p2 );

    SC_METHOD(thread_up_V_fu_306_p2);
    sensitive << ( cp_V );
    sensitive << ( side_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_fu_204_p2 );
    sensitive << ( tmp_s_reg_438 );
    sensitive << ( tmp_i_fu_241_p2 );
    sensitive << ( tmp_i_24_fu_277_p2 );
    sensitive << ( tmp_5_fu_397_p2 );
    sensitive << ( tmp_3_fu_372_p2 );

    ap_CS_fsm = "00000";
    ap_return_preg = "0";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "right_r_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, cp_V, "(port)cp_V");
    sc_trace(mVcdFile, pp_rot_V_address0, "(port)pp_rot_V_address0");
    sc_trace(mVcdFile, pp_rot_V_ce0, "(port)pp_rot_V_ce0");
    sc_trace(mVcdFile, pp_rot_V_we0, "(port)pp_rot_V_we0");
    sc_trace(mVcdFile, pp_rot_V_d0, "(port)pp_rot_V_d0");
    sc_trace(mVcdFile, pp_rot_V_q0, "(port)pp_rot_V_q0");
    sc_trace(mVcdFile, pp_tile_V_address0, "(port)pp_tile_V_address0");
    sc_trace(mVcdFile, pp_tile_V_ce0, "(port)pp_tile_V_ce0");
    sc_trace(mVcdFile, pp_tile_V_we0, "(port)pp_tile_V_we0");
    sc_trace(mVcdFile, pp_tile_V_d0, "(port)pp_tile_V_d0");
    sc_trace(mVcdFile, pp_tile_V_q0, "(port)pp_tile_V_q0");
    sc_trace(mVcdFile, avail_V_i, "(port)avail_V_i");
    sc_trace(mVcdFile, avail_V_o, "(port)avail_V_o");
    sc_trace(mVcdFile, avail_V_o_ap_vld, "(port)avail_V_o_ap_vld");
    sc_trace(mVcdFile, side_V, "(port)side_V");
    sc_trace(mVcdFile, tiles_V_address0, "(port)tiles_V_address0");
    sc_trace(mVcdFile, tiles_V_ce0, "(port)tiles_V_ce0");
    sc_trace(mVcdFile, tiles_V_q0, "(port)tiles_V_q0");
    sc_trace(mVcdFile, colours_V_address0, "(port)colours_V_address0");
    sc_trace(mVcdFile, colours_V_ce0, "(port)colours_V_ce0");
    sc_trace(mVcdFile, colours_V_q0, "(port)colours_V_q0");
    sc_trace(mVcdFile, ntiles_V, "(port)ntiles_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, tmp_fu_199_p1, "tmp_fu_199_p1");
    sc_trace(mVcdFile, tmp_reg_428, "tmp_reg_428");
    sc_trace(mVcdFile, pp_rot_V_addr_reg_433, "pp_rot_V_addr_reg_433");
    sc_trace(mVcdFile, tmp_s_fu_204_p2, "tmp_s_fu_204_p2");
    sc_trace(mVcdFile, tmp_s_reg_438, "tmp_s_reg_438");
    sc_trace(mVcdFile, pp_tile_V_addr_reg_442, "pp_tile_V_addr_reg_442");
    sc_trace(mVcdFile, pp_tile_V_load_reg_447, "pp_tile_V_load_reg_447");
    sc_trace(mVcdFile, possible_V_fu_224_p2, "possible_V_fu_224_p2");
    sc_trace(mVcdFile, possible_V_reg_452, "possible_V_reg_452");
    sc_trace(mVcdFile, left_V_fu_236_p2, "left_V_fu_236_p2");
    sc_trace(mVcdFile, left_V_reg_458, "left_V_reg_458");
    sc_trace(mVcdFile, tmp_i_fu_241_p2, "tmp_i_fu_241_p2");
    sc_trace(mVcdFile, tmp_i_reg_463, "tmp_i_reg_463");
    sc_trace(mVcdFile, tmp_40_tr_i_fu_250_p1, "tmp_40_tr_i_fu_250_p1");
    sc_trace(mVcdFile, tmp_i_24_fu_277_p2, "tmp_i_24_fu_277_p2");
    sc_trace(mVcdFile, tmp_i_24_reg_483, "tmp_i_24_reg_483");
    sc_trace(mVcdFile, tmp_26_reg_512, "tmp_26_reg_512");
    sc_trace(mVcdFile, agg_result_V_i1_fu_349_p3, "agg_result_V_i1_fu_349_p3");
    sc_trace(mVcdFile, agg_result_V_i1_reg_537, "agg_result_V_i1_reg_537");
    sc_trace(mVcdFile, tmp1_fu_360_p2, "tmp1_fu_360_p2");
    sc_trace(mVcdFile, tmp1_reg_547, "tmp1_reg_547");
    sc_trace(mVcdFile, t_V_fu_365_p2, "t_V_fu_365_p2");
    sc_trace(mVcdFile, agg_result_V_i_reg_145, "agg_result_V_i_reg_145");
    sc_trace(mVcdFile, p_058_0_in_reg_159, "p_058_0_in_reg_159");
    sc_trace(mVcdFile, tmp_5_fu_397_p2, "tmp_5_fu_397_p2");
    sc_trace(mVcdFile, tmp_3_fu_372_p2, "tmp_3_fu_372_p2");
    sc_trace(mVcdFile, p_0_phi_fu_172_p6, "p_0_phi_fu_172_p6");
    sc_trace(mVcdFile, p_0_reg_168, "p_0_reg_168");
    sc_trace(mVcdFile, tmp_i_i_fu_283_p1, "tmp_i_i_fu_283_p1");
    sc_trace(mVcdFile, tmp_20_fu_296_p1, "tmp_20_fu_296_p1");
    sc_trace(mVcdFile, tmp_30_i_fu_301_p1, "tmp_30_i_fu_301_p1");
    sc_trace(mVcdFile, tmp_i_i2_fu_319_p1, "tmp_i_i2_fu_319_p1");
    sc_trace(mVcdFile, tmp_22_fu_339_p1, "tmp_22_fu_339_p1");
    sc_trace(mVcdFile, tmp_i5_fu_344_p1, "tmp_i5_fu_344_p1");
    sc_trace(mVcdFile, tmp_6_fu_409_p2, "tmp_6_fu_409_p2");
    sc_trace(mVcdFile, grp_fu_184_p2, "grp_fu_184_p2");
    sc_trace(mVcdFile, tmp_1_fu_210_p1, "tmp_1_fu_210_p1");
    sc_trace(mVcdFile, r_V_fu_214_p2, "r_V_fu_214_p2");
    sc_trace(mVcdFile, grp_fu_254_p0, "grp_fu_254_p0");
    sc_trace(mVcdFile, grp_fu_254_p1, "grp_fu_254_p1");
    sc_trace(mVcdFile, grp_fu_263_p0, "grp_fu_263_p0");
    sc_trace(mVcdFile, grp_fu_263_p1, "grp_fu_263_p1");
    sc_trace(mVcdFile, grp_fu_254_p2, "grp_fu_254_p2");
    sc_trace(mVcdFile, grp_fu_263_p2, "grp_fu_263_p2");
    sc_trace(mVcdFile, r_V_5_fu_269_p1, "r_V_5_fu_269_p1");
    sc_trace(mVcdFile, r_V_8_fu_273_p1, "r_V_8_fu_273_p1");
    sc_trace(mVcdFile, tmp_19_fu_288_p3, "tmp_19_fu_288_p3");
    sc_trace(mVcdFile, up_V_fu_306_p2, "up_V_fu_306_p2");
    sc_trace(mVcdFile, r_V_7_fu_325_p2, "r_V_7_fu_325_p2");
    sc_trace(mVcdFile, tmp_21_fu_331_p3, "tmp_21_fu_331_p3");
    sc_trace(mVcdFile, tmp_4_fu_377_p1, "tmp_4_fu_377_p1");
    sc_trace(mVcdFile, r_V_10_fu_381_p2, "r_V_10_fu_381_p2");
    sc_trace(mVcdFile, tmp2_fu_387_p2, "tmp2_fu_387_p2");
    sc_trace(mVcdFile, r_V_2_fu_392_p2, "r_V_2_fu_392_p2");
    sc_trace(mVcdFile, p_s_fu_403_p2, "p_s_fu_403_p2");
    sc_trace(mVcdFile, toplevel_sdiv_9s_9ns_9_12_U11_ap_start, "toplevel_sdiv_9s_9ns_9_12_U11_ap_start");
    sc_trace(mVcdFile, grp_fu_254_ce, "grp_fu_254_ce");
    sc_trace(mVcdFile, toplevel_sdiv_9s_9ns_9_12_U12_ap_start, "toplevel_sdiv_9s_9ns_9_12_U12_ap_start");
    sc_trace(mVcdFile, grp_fu_263_ce, "grp_fu_263_ce");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_sig_bdd_390, "ap_sig_bdd_390");
    sc_trace(mVcdFile, ap_sig_bdd_157, "ap_sig_bdd_157");
#endif

    }
}

right_r::~right_r() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete toplevel_sdiv_9s_9ns_9_12_U11;
    delete toplevel_sdiv_9s_9ns_9_12_U12;
}

void right_r::thread_ap_clk_no_reset_() {
    if (((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_241_p2.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_24_fu_277_p2.read())))) {
        agg_result_V_i_reg_145 = ap_const_lv36_FFFFFFFFF;
    } else if ((esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_reg_463.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_24_reg_483.read()))) {
        agg_result_V_i_reg_145 = colours_V_q0.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv1_0;
    } else {
        if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
             (esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) || 
              esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) || 
              esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
            ap_return_preg = p_0_phi_fu_172_p6.read();
        }
    }
    if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read()))) {
        p_058_0_in_reg_159 = t_V_fu_365_p2.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read())) {
        p_058_0_in_reg_159 = pp_tile_V_load_reg_447.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read()))) {
        p_0_reg_168 = ap_const_lv1_0;
    } else if (((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                 esl_seteq<1,1,1>(tmp_s_fu_204_p2.read(), ap_const_lv1_0)) || 
                (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
                 !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
        p_0_reg_168 = ap_const_lv1_1;
    }
    if (esl_seteq<1,5,5>(ap_ST_st20_fsm_19, ap_CS_fsm.read())) {
        agg_result_V_i1_reg_537 = agg_result_V_i1_fu_349_p3.read();
        tmp1_reg_547 = tmp1_fu_360_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        left_V_reg_458 = left_V_fu_236_p2.read();
        possible_V_reg_452 = possible_V_fu_224_p2.read();
        pp_tile_V_load_reg_447 = pp_tile_V_q0.read();
        tmp_i_reg_463 = tmp_i_fu_241_p2.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        pp_rot_V_addr_reg_433 =  (sc_lv<6>) (tmp_fu_199_p1.read());
        tmp_reg_428 = tmp_fu_199_p1.read();
    }
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(tmp_s_fu_204_p2.read(), ap_const_lv1_0))) {
        pp_tile_V_addr_reg_442 =  (sc_lv<6>) (tmp_reg_428.read());
    }
    if (esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read())) {
        tmp_26_reg_512 = up_V_fu_306_p2.read().range(7, 7);
    }
    if (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) {
        tmp_i_24_reg_483 = tmp_i_24_fu_277_p2.read();
    }
    if (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        tmp_s_reg_438 = tmp_s_fu_204_p2.read();
    }
}

void right_r::thread_agg_result_V_i1_fu_349_p3() {
    agg_result_V_i1_fu_349_p3 = (!tmp_26_reg_512.read()[0].is_01())? sc_lv<36>(): ((tmp_26_reg_512.read()[0].to_bool())? ap_const_lv36_FFFFFFFFF: colours_V_q0.read());
}

void right_r::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) || 
         (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
          (esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) || 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) || 
           esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read()))))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void right_r::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void right_r::thread_ap_ready() {
    if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
         (esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void right_r::thread_ap_return() {
    if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
         (esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) || 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
        ap_return = p_0_phi_fu_172_p6.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void right_r::thread_ap_sig_bdd_157() {
    ap_sig_bdd_157 = (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0));
}

void right_r::thread_ap_sig_bdd_390() {
    ap_sig_bdd_390 = (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read()));
}

void right_r::thread_avail_V_o() {
    if ((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read()))) {
        avail_V_o = tmp_6_fu_409_p2.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        avail_V_o = possible_V_fu_224_p2.read();
    } else {
        avail_V_o = avail_V_i.read();
    }
}

void right_r::thread_avail_V_o_ap_vld() {
    if ((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) || 
         (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
        avail_V_o_ap_vld = ap_const_logic_1;
    } else {
        avail_V_o_ap_vld = ap_const_logic_0;
    }
}

void right_r::thread_colours_V_address0() {
    if (esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        colours_V_address0 =  (sc_lv<4>) (tmp_i5_fu_344_p1.read());
    } else if (esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read())) {
        colours_V_address0 =  (sc_lv<4>) (tmp_30_i_fu_301_p1.read());
    } else {
        colours_V_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void right_r::thread_colours_V_ce0() {
    if ((esl_seteq<1,5,5>(ap_ST_st16_fsm_15, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st19_fsm_18, ap_CS_fsm.read()))) {
        colours_V_ce0 = ap_const_logic_1;
    } else {
        colours_V_ce0 = ap_const_logic_0;
    }
}

void right_r::thread_grp_fu_184_p2() {
    grp_fu_184_p2 = (!pp_rot_V_q0.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_bigint<2>(pp_rot_V_q0.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void right_r::thread_grp_fu_254_ce() {
    grp_fu_254_ce = ap_const_logic_1;
}

void right_r::thread_grp_fu_254_p0() {
    grp_fu_254_p0 = esl_sext<9,8>(left_V_fu_236_p2.read());
}

void right_r::thread_grp_fu_254_p1() {
    grp_fu_254_p1 = tmp_40_tr_i_fu_250_p1.read();
}

void right_r::thread_grp_fu_263_ce() {
    grp_fu_263_ce = ap_const_logic_1;
}

void right_r::thread_grp_fu_263_p0() {
    grp_fu_263_p0 = esl_sext<9,8>(cp_V.read());
}

void right_r::thread_grp_fu_263_p1() {
    grp_fu_263_p1 = tmp_40_tr_i_fu_250_p1.read();
}

void right_r::thread_left_V_fu_236_p2() {
    left_V_fu_236_p2 = (!cp_V.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<8>(): (sc_bigint<8>(cp_V.read()) + sc_biguint<8>(ap_const_lv8_FF));
}

void right_r::thread_p_0_phi_fu_172_p6() {
    if (ap_sig_bdd_157.read()) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())) {
            p_0_phi_fu_172_p6 = ap_const_lv1_0;
        } else if (ap_sig_bdd_390.read()) {
            p_0_phi_fu_172_p6 = ap_const_lv1_1;
        } else {
            p_0_phi_fu_172_p6 = p_0_reg_168.read();
        }
    } else {
        p_0_phi_fu_172_p6 = p_0_reg_168.read();
    }
}

void right_r::thread_p_s_fu_403_p2() {
    p_s_fu_403_p2 = (r_V_10_fu_381_p2.read() ^ ap_const_lv36_FFFFFFFFF);
}

void right_r::thread_possible_V_fu_224_p2() {
    possible_V_fu_224_p2 = (avail_V_i.read() | r_V_fu_214_p2.read());
}

void right_r::thread_pp_rot_V_address0() {
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()))) {
        pp_rot_V_address0 = pp_rot_V_addr_reg_433.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read())) {
        pp_rot_V_address0 =  (sc_lv<6>) (tmp_i_i2_fu_319_p1.read());
    } else if (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) {
        pp_rot_V_address0 =  (sc_lv<6>) (tmp_i_i_fu_283_p1.read());
    } else if (esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) {
        pp_rot_V_address0 =  (sc_lv<6>) (tmp_fu_199_p1.read());
    } else {
        pp_rot_V_address0 = "XXXXXX";
    }
}

void right_r::thread_pp_rot_V_ce0() {
    if (((esl_seteq<1,5,5>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
         esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()))) {
        pp_rot_V_ce0 = ap_const_logic_1;
    } else {
        pp_rot_V_ce0 = ap_const_logic_0;
    }
}

void right_r::thread_pp_rot_V_d0() {
    if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        pp_rot_V_d0 = ap_const_lv2_0;
    } else if (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        pp_rot_V_d0 = grp_fu_184_p2.read();
    } else {
        pp_rot_V_d0 =  (sc_lv<2>) ("XX");
    }
}

void right_r::thread_pp_rot_V_we0() {
    if (((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(tmp_s_fu_204_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
        pp_rot_V_we0 = ap_const_logic_1;
    } else {
        pp_rot_V_we0 = ap_const_logic_0;
    }
}

void right_r::thread_pp_tile_V_address0() {
    if (esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        pp_tile_V_address0 = pp_tile_V_addr_reg_442.read();
    } else if (esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read())) {
        pp_tile_V_address0 =  (sc_lv<6>) (tmp_i_i2_fu_319_p1.read());
    } else if (esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read())) {
        pp_tile_V_address0 =  (sc_lv<6>) (tmp_i_i_fu_283_p1.read());
    } else if (esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        pp_tile_V_address0 =  (sc_lv<6>) (tmp_reg_428.read());
    } else {
        pp_tile_V_address0 = "XXXXXX";
    }
}

void right_r::thread_pp_tile_V_ce0() {
    if ((esl_seteq<1,5,5>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st17_fsm_16, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()))) {
        pp_tile_V_ce0 = ap_const_logic_1;
    } else {
        pp_tile_V_ce0 = ap_const_logic_0;
    }
}

void right_r::thread_pp_tile_V_d0() {
    pp_tile_V_d0 = t_V_fu_365_p2.read();
}

void right_r::thread_pp_tile_V_we0() {
    if (((esl_seteq<1,5,5>(ap_ST_st21_fsm_20, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read())))) {
        pp_tile_V_we0 = ap_const_logic_1;
    } else {
        pp_tile_V_we0 = ap_const_logic_0;
    }
}

void right_r::thread_r_V_10_fu_381_p2() {
    r_V_10_fu_381_p2 = (!tmp_4_fu_377_p1.read().is_01())? sc_lv<36>(): ap_const_lv36_1 << (unsigned short)tmp_4_fu_377_p1.read().to_uint();
}

void right_r::thread_r_V_2_fu_392_p2() {
    r_V_2_fu_392_p2 = (tmp2_fu_387_p2.read() & tmp1_reg_547.read());
}

void right_r::thread_r_V_5_fu_269_p1() {
    r_V_5_fu_269_p1 = grp_fu_254_p2.read().range(8-1, 0);
}

void right_r::thread_r_V_7_fu_325_p2() {
    r_V_7_fu_325_p2 = (pp_rot_V_q0.read() ^ ap_const_lv2_2);
}

void right_r::thread_r_V_8_fu_273_p1() {
    r_V_8_fu_273_p1 = grp_fu_263_p2.read().range(8-1, 0);
}

void right_r::thread_r_V_fu_214_p2() {
    r_V_fu_214_p2 = (!tmp_1_fu_210_p1.read().is_01())? sc_lv<36>(): ap_const_lv36_1 << (unsigned short)tmp_1_fu_210_p1.read().to_uint();
}

void right_r::thread_t_V_fu_365_p2() {
    t_V_fu_365_p2 = (!p_058_0_in_reg_159.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_bigint<8>(p_058_0_in_reg_159.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void right_r::thread_tiles_V_address0() {
    if (esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        tiles_V_address0 =  (sc_lv<8>) (tmp_22_fu_339_p1.read());
    } else if (esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read())) {
        tiles_V_address0 =  (sc_lv<8>) (tmp_20_fu_296_p1.read());
    } else {
        tiles_V_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void right_r::thread_tiles_V_ce0() {
    if ((esl_seteq<1,5,5>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) || 
         esl_seteq<1,5,5>(ap_ST_st18_fsm_17, ap_CS_fsm.read()))) {
        tiles_V_ce0 = ap_const_logic_1;
    } else {
        tiles_V_ce0 = ap_const_logic_0;
    }
}

void right_r::thread_tmp1_fu_360_p2() {
    tmp1_fu_360_p2 = (agg_result_V_i_reg_145.read() & possible_V_reg_452.read());
}

void right_r::thread_tmp2_fu_387_p2() {
    tmp2_fu_387_p2 = (agg_result_V_i1_reg_537.read() & r_V_10_fu_381_p2.read());
}

void right_r::thread_tmp_19_fu_288_p3() {
    tmp_19_fu_288_p3 = esl_concat<8,2>(pp_tile_V_q0.read(), grp_fu_184_p2.read());
}

void right_r::thread_tmp_1_fu_210_p1() {
    tmp_1_fu_210_p1 = esl_zext<36,8>(pp_tile_V_q0.read());
}

void right_r::thread_tmp_20_fu_296_p1() {
    tmp_20_fu_296_p1 = esl_zext<64,10>(tmp_19_fu_288_p3.read());
}

void right_r::thread_tmp_21_fu_331_p3() {
    tmp_21_fu_331_p3 = esl_concat<8,2>(pp_tile_V_q0.read(), r_V_7_fu_325_p2.read());
}

void right_r::thread_tmp_22_fu_339_p1() {
    tmp_22_fu_339_p1 = esl_zext<64,10>(tmp_21_fu_331_p3.read());
}

void right_r::thread_tmp_30_i_fu_301_p1() {
    tmp_30_i_fu_301_p1 = esl_zext<64,4>(tiles_V_q0.read());
}

void right_r::thread_tmp_3_fu_372_p2() {
    tmp_3_fu_372_p2 = (!t_V_fu_365_p2.read().is_01() || !ntiles_V.read().is_01())? sc_lv<1>(): (sc_biguint<8>(t_V_fu_365_p2.read()) < sc_biguint<8>(ntiles_V.read()));
}

void right_r::thread_tmp_40_tr_i_fu_250_p1() {
    tmp_40_tr_i_fu_250_p1 = esl_zext<9,8>(side_V.read());
}

void right_r::thread_tmp_4_fu_377_p1() {
    tmp_4_fu_377_p1 = esl_zext<36,8>(t_V_fu_365_p2.read());
}

void right_r::thread_tmp_5_fu_397_p2() {
    tmp_5_fu_397_p2 = (!r_V_2_fu_392_p2.read().is_01() || !ap_const_lv36_0.is_01())? sc_lv<1>(): sc_lv<1>(r_V_2_fu_392_p2.read() == ap_const_lv36_0);
}

void right_r::thread_tmp_6_fu_409_p2() {
    tmp_6_fu_409_p2 = (possible_V_reg_452.read() & p_s_fu_403_p2.read());
}

void right_r::thread_tmp_fu_199_p1() {
    tmp_fu_199_p1 = esl_sext<64,8>(cp_V.read());
}

void right_r::thread_tmp_i5_fu_344_p1() {
    tmp_i5_fu_344_p1 = esl_zext<64,4>(tiles_V_q0.read());
}

void right_r::thread_tmp_i_24_fu_277_p2() {
    tmp_i_24_fu_277_p2 = (!r_V_5_fu_269_p1.read().is_01() || !r_V_8_fu_273_p1.read().is_01())? sc_lv<1>(): sc_lv<1>(r_V_5_fu_269_p1.read() == r_V_8_fu_273_p1.read());
}

void right_r::thread_tmp_i_fu_241_p2() {
    tmp_i_fu_241_p2 = (!cp_V.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(cp_V.read() == ap_const_lv8_0);
}

void right_r::thread_tmp_i_i2_fu_319_p1() {
    tmp_i_i2_fu_319_p1 = esl_zext<64,8>(up_V_fu_306_p2.read());
}

void right_r::thread_tmp_i_i_fu_283_p1() {
    tmp_i_i_fu_283_p1 = esl_zext<64,8>(left_V_reg_458.read());
}

void right_r::thread_tmp_s_fu_204_p2() {
    tmp_s_fu_204_p2 = (!pp_rot_V_q0.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(pp_rot_V_q0.read() == ap_const_lv2_3);
}

void right_r::thread_toplevel_sdiv_9s_9ns_9_12_U11_ap_start() {
    if ((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_241_p2.read()))) {
        toplevel_sdiv_9s_9ns_9_12_U11_ap_start = ap_const_logic_1;
    } else {
        toplevel_sdiv_9s_9ns_9_12_U11_ap_start = ap_const_logic_0;
    }
}

void right_r::thread_toplevel_sdiv_9s_9ns_9_12_U12_ap_start() {
    if ((esl_seteq<1,5,5>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_241_p2.read()))) {
        toplevel_sdiv_9s_9ns_9_12_U12_ap_start = ap_const_logic_1;
    } else {
        toplevel_sdiv_9s_9ns_9_12_U12_ap_start = ap_const_logic_0;
    }
}

void right_r::thread_up_V_fu_306_p2() {
    up_V_fu_306_p2 = (!cp_V.read().is_01() || !side_V.read().is_01())? sc_lv<8>(): (sc_bigint<8>(cp_V.read()) - sc_biguint<8>(side_V.read()));
}

void right_r::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (esl_seteq<1,1,1>(tmp_s_fu_204_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_fu_241_p2.read())) {
                ap_NS_fsm = ap_ST_st17_fsm_16;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 13 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_24_fu_277_p2.read())) {
                ap_NS_fsm = ap_ST_st17_fsm_16;
            } else {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            }
            break;
        case 14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 20 : 
            if ((esl_seteq<1,1,1>(tmp_s_reg_438.read(), ap_const_lv1_0) || esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_397_p2.read()) || esl_seteq<1,1,1>(ap_const_lv1_0, tmp_3_fu_372_p2.read()))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st21_fsm_20;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}
}

