// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _toplevel_HH_
#define _toplevel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "solve.h"
#include "toplevel_tiles_V.h"
#include "toplevel_colours_V.h"
#include "toplevel_pp_tile_V.h"
#include "toplevel_pp_rot_V.h"

namespace ap_rtl {

struct toplevel : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<32> > input_V_V_dout;
    sc_in< sc_logic > input_V_V_empty_n;
    sc_out< sc_logic > input_V_V_read;
    sc_out< sc_lv<32> > output_V_V_din;
    sc_in< sc_logic > output_V_V_full_n;
    sc_out< sc_logic > output_V_V_write;


    // Module declarations
    toplevel(sc_module_name name);
    SC_HAS_PROCESS(toplevel);

    ~toplevel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    toplevel_tiles_V* tiles_V_U;
    toplevel_colours_V* colours_V_U;
    toplevel_pp_tile_V* pp_tile_V_U;
    toplevel_pp_rot_V* pp_rot_V_U;
    solve* grp_solve_fu_239;
    sc_signal< sc_lv<8> > cp_V;
    sc_signal< sc_lv<36> > avail_V;
    sc_signal< sc_lv<8> > side_V;
    sc_signal< sc_lv<8> > tiles_V_address0;
    sc_signal< sc_logic > tiles_V_ce0;
    sc_signal< sc_logic > tiles_V_we0;
    sc_signal< sc_lv<4> > tiles_V_d0;
    sc_signal< sc_lv<4> > tiles_V_q0;
    sc_signal< sc_lv<8> > tiles_V_address1;
    sc_signal< sc_logic > tiles_V_ce1;
    sc_signal< sc_lv<4> > tiles_V_q1;
    sc_signal< sc_lv<4> > colours_V_address0;
    sc_signal< sc_logic > colours_V_ce0;
    sc_signal< sc_logic > colours_V_we0;
    sc_signal< sc_lv<36> > colours_V_d0;
    sc_signal< sc_lv<36> > colours_V_q0;
    sc_signal< sc_lv<4> > colours_V_address1;
    sc_signal< sc_logic > colours_V_ce1;
    sc_signal< sc_lv<36> > colours_V_q1;
    sc_signal< sc_lv<6> > pp_tile_V_address0;
    sc_signal< sc_logic > pp_tile_V_ce0;
    sc_signal< sc_logic > pp_tile_V_we0;
    sc_signal< sc_lv<8> > pp_tile_V_d0;
    sc_signal< sc_lv<8> > pp_tile_V_q0;
    sc_signal< sc_lv<6> > pp_tile_V_address1;
    sc_signal< sc_logic > pp_tile_V_ce1;
    sc_signal< sc_lv<8> > pp_tile_V_q1;
    sc_signal< sc_lv<6> > pp_rot_V_address0;
    sc_signal< sc_logic > pp_rot_V_ce0;
    sc_signal< sc_logic > pp_rot_V_we0;
    sc_signal< sc_lv<2> > pp_rot_V_d0;
    sc_signal< sc_lv<2> > pp_rot_V_q0;
    sc_signal< sc_lv<6> > pp_rot_V_address1;
    sc_signal< sc_logic > pp_rot_V_ce1;
    sc_signal< sc_lv<2> > pp_rot_V_q1;
    sc_signal< sc_lv<6> > t_fu_273_p2;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_lv<1> > exitcond_i_fu_267_p2;
    sc_signal< bool > ap_sig_bdd_95;
    sc_signal< sc_lv<8> > t_V_1_fu_335_p2;
    sc_signal< sc_lv<8> > t_V_1_reg_579;
    sc_signal< sc_lv<3> > e_V_fu_347_p2;
    sc_signal< sc_lv<1> > exitcond1_fu_341_p2;
    sc_signal< bool > ap_sig_bdd_107;
    sc_signal< sc_lv<32> > t_1_fu_405_p2;
    sc_signal< sc_lv<32> > t_1_reg_595;
    sc_signal< sc_lv<36> > r_V_4_fu_445_p3;
    sc_signal< sc_lv<36> > r_V_4_reg_600;
    sc_signal< sc_lv<1> > tmp_1_i_fu_399_p2;
    sc_signal< sc_lv<3> > e_fu_459_p2;
    sc_signal< sc_lv<3> > e_reg_608;
    sc_signal< sc_lv<1> > exitcond_i9_fu_453_p2;
    sc_signal< sc_lv<4> > colours_V_addr_reg_618;
    sc_signal< sc_lv<8> > p_V_fu_517_p2;
    sc_signal< sc_lv<8> > p_V_reg_626;
    sc_signal< sc_lv<6> > pp_tile_V_addr_reg_631;
    sc_signal< sc_lv<1> > tmp_7_fu_511_p2;
    sc_signal< sc_lv<6> > pp_rot_V_addr_reg_636;
    sc_signal< sc_lv<3> > e_V_1_fu_535_p2;
    sc_signal< sc_lv<3> > e_V_1_reg_644;
    sc_signal< sc_lv<2> > tmp_11_fu_541_p1;
    sc_signal< sc_lv<2> > tmp_11_reg_649;
    sc_signal< sc_lv<1> > exitcond_fu_529_p2;
    sc_signal< sc_logic > grp_solve_fu_239_ap_start;
    sc_signal< sc_logic > grp_solve_fu_239_ap_done;
    sc_signal< sc_logic > grp_solve_fu_239_ap_idle;
    sc_signal< sc_logic > grp_solve_fu_239_ap_ready;
    sc_signal< sc_lv<36> > grp_solve_fu_239_avail_V_i;
    sc_signal< sc_lv<36> > grp_solve_fu_239_avail_V_o;
    sc_signal< sc_logic > grp_solve_fu_239_avail_V_o_ap_vld;
    sc_signal< sc_lv<8> > grp_solve_fu_239_side_V;
    sc_signal< sc_lv<8> > grp_solve_fu_239_cp_V_i;
    sc_signal< sc_lv<8> > grp_solve_fu_239_cp_V_o;
    sc_signal< sc_logic > grp_solve_fu_239_cp_V_o_ap_vld;
    sc_signal< sc_lv<6> > grp_solve_fu_239_pp_tile_V_address0;
    sc_signal< sc_logic > grp_solve_fu_239_pp_tile_V_ce0;
    sc_signal< sc_logic > grp_solve_fu_239_pp_tile_V_we0;
    sc_signal< sc_lv<8> > grp_solve_fu_239_pp_tile_V_d0;
    sc_signal< sc_lv<8> > grp_solve_fu_239_pp_tile_V_q0;
    sc_signal< sc_lv<6> > grp_solve_fu_239_pp_tile_V_address1;
    sc_signal< sc_logic > grp_solve_fu_239_pp_tile_V_ce1;
    sc_signal< sc_lv<8> > grp_solve_fu_239_pp_tile_V_q1;
    sc_signal< sc_lv<6> > grp_solve_fu_239_pp_rot_V_address0;
    sc_signal< sc_logic > grp_solve_fu_239_pp_rot_V_ce0;
    sc_signal< sc_logic > grp_solve_fu_239_pp_rot_V_we0;
    sc_signal< sc_lv<2> > grp_solve_fu_239_pp_rot_V_d0;
    sc_signal< sc_lv<2> > grp_solve_fu_239_pp_rot_V_q0;
    sc_signal< sc_lv<6> > grp_solve_fu_239_pp_rot_V_address1;
    sc_signal< sc_logic > grp_solve_fu_239_pp_rot_V_ce1;
    sc_signal< sc_lv<2> > grp_solve_fu_239_pp_rot_V_q1;
    sc_signal< sc_lv<8> > grp_solve_fu_239_tiles_V_address0;
    sc_signal< sc_logic > grp_solve_fu_239_tiles_V_ce0;
    sc_signal< sc_lv<4> > grp_solve_fu_239_tiles_V_q0;
    sc_signal< sc_lv<8> > grp_solve_fu_239_tiles_V_address1;
    sc_signal< sc_logic > grp_solve_fu_239_tiles_V_ce1;
    sc_signal< sc_lv<4> > grp_solve_fu_239_tiles_V_q1;
    sc_signal< sc_lv<4> > grp_solve_fu_239_colours_V_address0;
    sc_signal< sc_logic > grp_solve_fu_239_colours_V_ce0;
    sc_signal< sc_lv<36> > grp_solve_fu_239_colours_V_q0;
    sc_signal< sc_lv<4> > grp_solve_fu_239_colours_V_address1;
    sc_signal< sc_logic > grp_solve_fu_239_colours_V_ce1;
    sc_signal< sc_lv<36> > grp_solve_fu_239_colours_V_q1;
    sc_signal< sc_lv<6> > op2_assign_reg_159;
    sc_signal< sc_lv<8> > t_V_reg_170;
    sc_signal< sc_lv<3> > t_V_2_reg_182;
    sc_signal< sc_lv<1> > tmp_2_fu_329_p2;
    sc_signal< sc_lv<32> > op2_assign_1_reg_193;
    sc_signal< sc_lv<3> > e_i_reg_205;
    sc_signal< sc_lv<8> > t_V_3_reg_216;
    sc_signal< sc_lv<3> > t_V_4_reg_227;
    sc_signal< sc_logic > grp_solve_fu_239_ap_start_ap_start_reg;
    sc_signal< sc_lv<64> > tmp_1_fu_380_p1;
    sc_signal< sc_lv<64> > tmp_4_fu_481_p1;
    sc_signal< sc_lv<64> > tmp_9_i1_fu_486_p1;
    sc_signal< sc_lv<64> > tmp_i1_fu_523_p1;
    sc_signal< sc_lv<64> > tmp_6_fu_558_p1;
    sc_signal< sc_lv<36> > tmp_9_i_fu_293_p2;
    sc_signal< sc_lv<8> > tmp_3_fu_305_p1;
    sc_signal< sc_lv<36> > tmp_i_fu_279_p1;
    sc_signal< sc_lv<36> > r_V_2_fu_283_p2;
    sc_signal< sc_lv<8> > r_V_fu_319_p0;
    sc_signal< sc_lv<16> > lhs_V_fu_315_p1;
    sc_signal< sc_lv<8> > r_V_fu_319_p1;
    sc_signal< sc_lv<16> > tmp_cast_fu_325_p1;
    sc_signal< sc_lv<16> > r_V_fu_319_p2;
    sc_signal< sc_lv<10> > tmp_fu_362_p3;
    sc_signal< sc_lv<11> > tiles_V_addr5_cast_fu_370_p1;
    sc_signal< sc_lv<11> > tmp_9_trn_cast_fu_358_p1;
    sc_signal< sc_lv<11> > tiles_V_addr6_fu_374_p2;
    sc_signal< sc_lv<8> > r_V_3_fu_389_p0;
    sc_signal< sc_lv<16> > lhs_V_1_fu_385_p1;
    sc_signal< sc_lv<8> > r_V_3_fu_389_p1;
    sc_signal< sc_lv<16> > r_V_3_fu_389_p2;
    sc_signal< sc_lv<32> > tmp_i5_cast_fu_395_p1;
    sc_signal< sc_lv<36> > tmp_3_i_fu_419_p1;
    sc_signal< sc_lv<32> > tmp_5_i6_fu_429_p2;
    sc_signal< sc_lv<32> > tmp_7_i8_fu_435_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_411_p3;
    sc_signal< sc_lv<36> > tmp_7_i8_cast_fu_441_p1;
    sc_signal< sc_lv<36> > tmp_4_i_fu_423_p2;
    sc_signal< sc_lv<32> > tmp_10_fu_469_p2;
    sc_signal< sc_lv<32> > tmp_8_i1_trn_fu_465_p1;
    sc_signal< sc_lv<32> > tiles_V_addr4_fu_475_p2;
    sc_signal< sc_lv<8> > r_V_1_fu_501_p0;
    sc_signal< sc_lv<16> > lhs_V_2_fu_497_p1;
    sc_signal< sc_lv<8> > r_V_1_fu_501_p1;
    sc_signal< sc_lv<16> > tmp_5_cast_fu_507_p1;
    sc_signal< sc_lv<16> > r_V_1_fu_501_p2;
    sc_signal< sc_lv<2> > r_V_5_fu_545_p2;
    sc_signal< sc_lv<10> > tmp_5_fu_550_p3;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_st1_fsm_0;
    static const sc_lv<4> ap_ST_st2_fsm_1;
    static const sc_lv<4> ap_ST_st3_fsm_2;
    static const sc_lv<4> ap_ST_st4_fsm_3;
    static const sc_lv<4> ap_ST_st5_fsm_4;
    static const sc_lv<4> ap_ST_st6_fsm_5;
    static const sc_lv<4> ap_ST_st7_fsm_6;
    static const sc_lv<4> ap_ST_st8_fsm_7;
    static const sc_lv<4> ap_ST_st9_fsm_8;
    static const sc_lv<4> ap_ST_st10_fsm_9;
    static const sc_lv<4> ap_ST_st11_fsm_10;
    static const sc_lv<4> ap_ST_st12_fsm_11;
    static const sc_lv<4> ap_ST_st13_fsm_12;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<6> ap_const_lv6_24;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<36> ap_const_lv36_1;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_sig_bdd_107();
    void thread_ap_sig_bdd_95();
    void thread_colours_V_address0();
    void thread_colours_V_address1();
    void thread_colours_V_ce0();
    void thread_colours_V_ce1();
    void thread_colours_V_d0();
    void thread_colours_V_we0();
    void thread_e_V_1_fu_535_p2();
    void thread_e_V_fu_347_p2();
    void thread_e_fu_459_p2();
    void thread_exitcond1_fu_341_p2();
    void thread_exitcond_fu_529_p2();
    void thread_exitcond_i9_fu_453_p2();
    void thread_exitcond_i_fu_267_p2();
    void thread_grp_solve_fu_239_ap_start();
    void thread_grp_solve_fu_239_avail_V_i();
    void thread_grp_solve_fu_239_colours_V_q0();
    void thread_grp_solve_fu_239_colours_V_q1();
    void thread_grp_solve_fu_239_cp_V_i();
    void thread_grp_solve_fu_239_pp_rot_V_q0();
    void thread_grp_solve_fu_239_pp_rot_V_q1();
    void thread_grp_solve_fu_239_pp_tile_V_q0();
    void thread_grp_solve_fu_239_pp_tile_V_q1();
    void thread_grp_solve_fu_239_side_V();
    void thread_grp_solve_fu_239_tiles_V_q0();
    void thread_grp_solve_fu_239_tiles_V_q1();
    void thread_input_V_V_read();
    void thread_lhs_V_1_fu_385_p1();
    void thread_lhs_V_2_fu_497_p1();
    void thread_lhs_V_fu_315_p1();
    void thread_output_V_V_din();
    void thread_output_V_V_write();
    void thread_p_V_fu_517_p2();
    void thread_pp_rot_V_address0();
    void thread_pp_rot_V_address1();
    void thread_pp_rot_V_ce0();
    void thread_pp_rot_V_ce1();
    void thread_pp_rot_V_d0();
    void thread_pp_rot_V_we0();
    void thread_pp_tile_V_address0();
    void thread_pp_tile_V_address1();
    void thread_pp_tile_V_ce0();
    void thread_pp_tile_V_ce1();
    void thread_pp_tile_V_d0();
    void thread_pp_tile_V_we0();
    void thread_r_V_1_fu_501_p0();
    void thread_r_V_1_fu_501_p1();
    void thread_r_V_1_fu_501_p2();
    void thread_r_V_2_fu_283_p2();
    void thread_r_V_3_fu_389_p0();
    void thread_r_V_3_fu_389_p1();
    void thread_r_V_3_fu_389_p2();
    void thread_r_V_4_fu_445_p3();
    void thread_r_V_5_fu_545_p2();
    void thread_r_V_fu_319_p0();
    void thread_r_V_fu_319_p1();
    void thread_r_V_fu_319_p2();
    void thread_t_1_fu_405_p2();
    void thread_t_V_1_fu_335_p2();
    void thread_t_fu_273_p2();
    void thread_tiles_V_addr4_fu_475_p2();
    void thread_tiles_V_addr5_cast_fu_370_p1();
    void thread_tiles_V_addr6_fu_374_p2();
    void thread_tiles_V_address0();
    void thread_tiles_V_address1();
    void thread_tiles_V_ce0();
    void thread_tiles_V_ce1();
    void thread_tiles_V_d0();
    void thread_tiles_V_we0();
    void thread_tmp_10_fu_469_p2();
    void thread_tmp_11_fu_541_p1();
    void thread_tmp_1_fu_380_p1();
    void thread_tmp_1_i_fu_399_p2();
    void thread_tmp_2_fu_329_p2();
    void thread_tmp_3_fu_305_p1();
    void thread_tmp_3_i_fu_419_p1();
    void thread_tmp_4_fu_481_p1();
    void thread_tmp_4_i_fu_423_p2();
    void thread_tmp_5_cast_fu_507_p1();
    void thread_tmp_5_fu_550_p3();
    void thread_tmp_5_i6_fu_429_p2();
    void thread_tmp_6_fu_558_p1();
    void thread_tmp_7_fu_511_p2();
    void thread_tmp_7_i8_cast_fu_441_p1();
    void thread_tmp_7_i8_fu_435_p2();
    void thread_tmp_8_i1_trn_fu_465_p1();
    void thread_tmp_9_fu_411_p3();
    void thread_tmp_9_i1_fu_486_p1();
    void thread_tmp_9_i_fu_293_p2();
    void thread_tmp_9_trn_cast_fu_358_p1();
    void thread_tmp_cast_fu_325_p1();
    void thread_tmp_fu_362_p3();
    void thread_tmp_i1_fu_523_p1();
    void thread_tmp_i5_cast_fu_395_p1();
    void thread_tmp_i_fu_279_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
