// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.4
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

`timescale 1 ns / 1 ps
module toplevel_top (
input_V_V_TVALID,
input_V_V_TREADY,
input_V_V_TDATA,
output_V_V_TVALID,
output_V_V_TREADY,
output_V_V_TDATA,
aresetn,
aclk
);

parameter RESET_ACTIVE_LOW = 1;

input input_V_V_TVALID ;
output input_V_V_TREADY ;
input [32 - 1:0] input_V_V_TDATA ;


output output_V_V_TVALID ;
input output_V_V_TREADY ;
output [32 - 1:0] output_V_V_TDATA ;

input aresetn ;

input aclk ;


wire input_V_V_TVALID;
wire input_V_V_TREADY;
wire [32 - 1:0] input_V_V_TDATA;


wire output_V_V_TVALID;
wire output_V_V_TREADY;
wire [32 - 1:0] output_V_V_TDATA;

wire aresetn;


wire [32 - 1:0] sig_toplevel_input_V_V_dout;
wire sig_toplevel_input_V_V_empty_n;
wire sig_toplevel_input_V_V_read;

wire [32 - 1:0] sig_toplevel_output_V_V_din;
wire sig_toplevel_output_V_V_full_n;
wire sig_toplevel_output_V_V_write;

wire sig_toplevel_ap_rst;



toplevel toplevel_U(
    .input_V_V_dout(sig_toplevel_input_V_V_dout),
    .input_V_V_empty_n(sig_toplevel_input_V_V_empty_n),
    .input_V_V_read(sig_toplevel_input_V_V_read),
    .output_V_V_din(sig_toplevel_output_V_V_din),
    .output_V_V_full_n(sig_toplevel_output_V_V_full_n),
    .output_V_V_write(sig_toplevel_output_V_V_write),
    .ap_rst(sig_toplevel_ap_rst),
    .ap_clk(aclk)
);

toplevel_input_V_V_if toplevel_input_V_V_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .input_V_V_dout(sig_toplevel_input_V_V_dout),
    .input_V_V_empty_n(sig_toplevel_input_V_V_empty_n),
    .input_V_V_read(sig_toplevel_input_V_V_read),
    .TVALID(input_V_V_TVALID),
    .TREADY(input_V_V_TREADY),
    .TDATA(input_V_V_TDATA));

toplevel_output_V_V_if toplevel_output_V_V_if_U(
    .ACLK(aclk),
    .ARESETN(aresetn),
    .output_V_V_din(sig_toplevel_output_V_V_din),
    .output_V_V_full_n(sig_toplevel_output_V_V_full_n),
    .output_V_V_write(sig_toplevel_output_V_V_write),
    .TVALID(output_V_V_TVALID),
    .TREADY(output_V_V_TREADY),
    .TDATA(output_V_V_TDATA));

toplevel_ap_rst_if #(
    .RESET_ACTIVE_LOW(RESET_ACTIVE_LOW))
ap_rst_if_U(
    .dout(sig_toplevel_ap_rst),
    .din(aresetn));

endmodule
